<html>
<head>
    <title>Business Rules Manager</title>
</head>

<body>
    <h1>Business Rules Manager</h1>
    
    <p>Select an option:</p>
    
    <a href = "<?php echo $this->baseUrl() . "view"; ?>" >View Business Rules</a>
    <br><br>
    <a href = "<?php echo $this->baseUrl() . "create"; ?>" >Create Business Rules</a>
    <br><br>
    <a href = "<?php echo $this->baseUrl() . "associate"; ?>" >Associate Business Rules to Access Types</a>
    
</body>
    
</html>